"""Initial migration

Revision ID: fd64713d5241
Revises:
Create Date: 2025-09-07 04:08:12.571802

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fd64713d5241"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mira_networks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("service_enabled", sa.Boolean(), nullable=True),
        sa.Column("network_settings", sa.JSON(), nullable=True),
        sa.Column("connected_clients", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_ids", sa.JSON(), nullable=True),
        sa.Column("topic_summary", sa.Text(), nullable=True),
        sa.Column("context_summary", sa.Text(), nullable=True),
        sa.Column("network_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["mira_networks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "persons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("voice_embedding", sa.JSON(), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=True),
        sa.Column("network_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["mira_networks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("index"),
    )
    op.create_table(
        "interactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("conversation_id", sa.UUID(), nullable=True),
        sa.Column("voice_embedding", sa.JSON(), nullable=True),
        sa.Column("speaker_id", sa.UUID(), nullable=True),
        sa.Column("text_embedding", sa.JSON(), nullable=True),
        sa.Column("entities", sa.JSON(), nullable=True),
        sa.Column("topics", sa.JSON(), nullable=True),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.Column("network_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["network_id"],
            ["mira_networks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "person_conversation",
        sa.Column("person_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
        ),
        sa.PrimaryKeyConstraint("person_id", "conversation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person_conversation")
    op.drop_table("interactions")
    op.drop_table("persons")
    op.drop_table("conversations")
    op.drop_table("mira_networks")
    # ### end Alembic commands ###
