FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

RUN microdnf install -y \
    gcc \
    gcc-c++ \
    libpq-devel \
    git \
    && microdnf clean all

COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app ./app

COPY ./alembic ./alembic
COPY alembic.ini .

ENV PYTHONPATH="${LAMBDA_TASK_ROOT}:${PYTHONPATH}"

CMD ["app.main.handler"]