FROM public.ecr.aws/lambda/python:3.12

WORKDIR /var/task

RUN yum -y update && yum install -y \
    gcc \
    gcc-c++ \
    libpq-devel \
    git \
    curl \
    && yum clean all

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY app/ ./app
COPY alembic.ini .
COPY alembic/ ./alembic

CMD ["app.main.handler"]