version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../app:/app/app:cached            # Mount app code for live reload
      - ../requirements.txt:/app/requirements.txt:cached
      - ../alembic:/app/alembic:cached
      - ../.env:/app/.env:cached
      - ../pyproject.toml:/app/pyproject.toml:cached
      - ../Makefile:/app/Makefile:cached
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - DATABASE_URL=${DATABASE_URL}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - mira-network

networks:
  mira-network:
    driver: bridge
