name: CD Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change if needed

      # Build the Docker image
      - name: Build Docker image
        run: docker build -t mira-api:${{ github.sha }} -f docker/Dockerfile.lambda .

      # Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Tag & push image to ECR
      - name: Tag and push Docker image
        run: |
          docker tag mira-api:${{ github.sha }} 210291640622.dkr.ecr.us-east-1.amazonaws.com/mira-api:${{ github.sha }}
          docker push 210291640622.dkr.ecr.us-east-1.amazonaws.com/mira-api:${{ github.sha }}

      # Run Alembic migrations
      - name: Run Alembic migrations
        run: |
          docker run --rm \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            210291640622.dkr.ecr.us-east-1.amazonaws.com/mira-api:${{ github.sha }} \
            alembic upgrade head

      # Deploy to Lambda
      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name mira-backend-prod \
            --image-uri 210291640622.dkr.ecr.us-east-1.amazonaws.com/mira-api:${{ github.sha }}
