name: CI Pipeline

on:
  push:
    branches:
        - '**'
  pull_request:
    branches:
        - '**'

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    