name: Continuous Integration Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  integrate:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API Docker Image
        run: make build

      - name: Run Unit Tests
        run: make test

      - name: Lint Code
        run: make lint
