name: Mira Backend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test backend
        run: |
          # Build the Docker image
          docker build -t mira-backend -f Dockerfile .

          # Run linting and tests in container
          docker run --rm mira-backend flake8 .
          docker run --rm mira-backend pytest --cov=app --cov-report=xml --cov-report=term-missing

          # Extract coverage report from container
          docker cp $(docker create --rm mira-backend):/app/coverage.xml ./coverage.xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Security scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'mira-backend'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Test container startup
        run: |
          # Start the container
          docker run -d --name mira-test -p 8000:8000 mira-backend

          # Wait for container to be healthy
          timeout 30s bash -c 'while ! curl -s http://localhost:8000/health; do sleep 1; done'

          # Run basic health check
          curl -f http://localhost:8000/health || exit 1

          # Cleanup
          docker stop mira-test
          docker rm mira-test